# Form implementation generated from reading ui file 'pyqt/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 184)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.octaves_spin_box = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.octaves_spin_box.setMinimum(1)
        self.octaves_spin_box.setObjectName("octaves_spin_box")
        self.horizontalLayout_2.addWidget(self.octaves_spin_box)
        self.octaves_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.octaves_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.octaves_label.setObjectName("octaves_label")
        self.horizontalLayout_2.addWidget(self.octaves_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.port_line_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port_line_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.port_line_edit.setObjectName("port_line_edit")
        self.verticalLayout.addWidget(self.port_line_edit)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.done_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.done_button.setObjectName("done_button")
        self.verticalLayout_3.addWidget(self.done_button)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buzzer Piano Launcher"))
        self.octaves_label.setText(_translate("MainWindow", "Octaves"))
        self.port_line_edit.setPlaceholderText(_translate("MainWindow", "Enter MCU port"))
        self.done_button.setText(_translate("MainWindow", "DONE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
